AWSTemplateFormatVersion: 2010-09-09
Description: Deploying resources for assignment 3
Parameters:
  S3InputBucketName:
    Type: String
    Default: input-bucket-psg
  S3CrawlerBucketName:
    Type: String
    Default: crawler-bucket-psg
  S3OutputAthenaBucketName:
    Type: String
    Default: output-athena-psg
  CodeGlueBucket:
    Type: String
    Default: code-bucket-psg
  CName:
    Type: String
    Default: crawler-psg
  GlueJobCsvFileName:
    Type: String
    Default: glue-job-csv.py
  GlueJobJsonFileName:
    Type: String
    Default: glue-job-json.py
  DynamoTableName:
    Type: String
    Default: glueTable
  DatabaseName:
    Type: String
    Default: databasepsg
  LambdaCrawlerKey:
    Type: String
    Default: lambda-crawler.zip
  LambdaCrawlerHandler:
    Type: String
    Default: lambda_handler.handler
  LambdaGlueKey:
    Type: String
    Default: lambda-glue.zip
  LambdaGlueHandler:
    Type: String
    Default: lambda_handler.handler
  GlueJobCsvName:
    Type: String
    Default: glue-job-csv
  GlueJobJsonName:
    Type: String
    Default: glue-job-json
Resources:
  S3InputBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref S3InputBucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt GlueLambda.Arn
  S3CrawlerBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref S3CrawlerBucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt CrawlerLambda.Arn
  S3OutputAthenaBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref S3OutputAthenaBucketName
  GlueLambdaPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !GetAtt GlueLambda.Arn
      Action: 'lambda:InvokeFunction'
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn:
        'Fn::Sub': 'arn:aws:s3:::${S3InputBucketName}'
  CrawlerLambdaPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !GetAtt CrawlerLambda.Arn
      Action: 'lambda:InvokeFunction'
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn:
        'Fn::Sub': 'arn:aws:s3:::${S3CrawlerBucketName}'
  GlueLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Environment:
        Variables:
          dynamotablename: !Ref DynamoTableName
      Code:
        S3Bucket: !Ref CodeGlueBucket
        S3Key: !Ref LambdaGlueKey
      Runtime: python3.13
      Handler: !Ref LambdaGlueHandler
      Role: !GetAtt LambdaIAM.Arn
      Timeout: 300
  CrawlerLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Environment:
        Variables:
          crawlername: !Ref CName
          outputbucket: !Ref S3OutputAthenaBucketName
          databasename: !Ref DatabaseName
      Code:
        S3Bucket: !Ref CodeGlueBucket
        S3Key: !Ref LambdaCrawlerKey
      Runtime: python3.13
      Handler: !Ref LambdaCrawlerHandler
      Role: !GetAtt LambdaIAM.Arn
      Timeout: 300
  DataBase:
    Type: "AWS::Glue::Database"
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref DatabaseName
  Crawler:
    Type: "AWS::Glue::Crawler"
    Properties:
      Name: !Ref CName
      Role: !GetAtt GlueIAM.Arn
      DatabaseName: !Ref DatabaseName
      Targets:
        S3Targets:
          - Path: !Ref S3CrawlerBucketName
  DynamoDbTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Ref DynamoTableName
      AttributeDefinitions:
        - AttributeName: "fileType"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "fileType"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
  GlueJobJson:
    Type: "AWS::Glue::Job"
    Properties:
      Name: !Ref GlueJobJsonName
      Role: !GetAtt GlueIAM.Arn
      GlueVersion: 4.0
      WorkerType: G.1X
      NumberOfWorkers: 2
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://${CodeGlueBucket}/${GlueJobJsonFileName}"
      DefaultArguments: {
        "--s3_input": !Sub "s3://${S3InputBucketName}/",
        "--file_name": "value_random",
        "--s3_output_path": !Sub "s3://${S3CrawlerBucketName}"
      }
  GlueJobCsv:
    Type: "AWS::Glue::Job"
    Properties:
      Name: !Ref GlueJobCsvName
      Role: !GetAtt GlueIAM.Arn
      GlueVersion: 4.0
      WorkerType: G.1X
      NumberOfWorkers: 2
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://${CodeGlueBucket}/${GlueJobCsvFileName}"
      DefaultArguments: {
        "--s3_input": !Sub "s3://${S3InputBucketName}/",
        "--file_name": "value_random",
        "--s3_output_path": !Sub "s3://${S3CrawlerBucketName}"
      }
  LambdaIAM:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "cf-a3-glue-lambda-s3-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
                - 'sts:AssumeRole'
      Policies:
        - PolicyName: "cf-assign3-glue-lambda-s3-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "dynamodb:GetItem"
                  - "glue:GetDatabase"
                  - "glue:GetTables"
                  - "glue:StartCrawler"
                  - "glue:GetCrawler"
                  - "glue:GetJobRun"
                  - "glue:StartJobRun"
                  - "athena:StartQueryExecution"
                Resource:
                  - !Sub "arn:aws:s3:::${S3InputBucketName}/*"
                  - !Sub "arn:aws:s3:::${S3CrawlerBucketName}/*"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoTableName}"
                  - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:crawler/${CName}"
                  - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/${DatabaseName}"
                  - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/${DatabaseName}/*"
                  - !Sub "arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/primary"
                  - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:job/${GlueJobCsvName}"
                  - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:job/${GlueJobJsonName}"
                  - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
  GlueIAM:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "cf-a3-glue-s3-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: "cf-assign3-glue-s3-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "glue:CreateTable"
                  - "glue:UpdateTable"
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
                  - !Sub "arn:aws:s3:::${S3InputBucketName}/*"
                  - !Sub "arn:aws:s3:::${S3CrawlerBucketName}/*"
                  #- !Sub "arn:aws:s3:::${S3OutputAthenaBucketName}/*"
                  - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/${DatabaseName}"
                  - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/${DatabaseName}/*"
                  #- !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:job/${GlueJobCsvFileName}"
                  #- !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:job/${GlueJobJsonFileName}"
                  - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog"
